# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  # - traindata
  # - testdata
  - paths: move.yaml
  - hydra: default.yaml
  - experiment: multi_overfit
  - traindata: hot3d_train.yaml
  - testdata: hot3d_mini.yaml


# This is just a placeholder to create the 'traindata' config node.
# It will be overridden by the actual dataset config.
# You can leave it empty or add a default target.


# task name, determines output directory path
task_name: ${expname}
expname: ft
exp_dir: ${paths.output_dir}/${expname}
log: wandb

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: False

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null