# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
# root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
# data_dir: ${paths.root_dir}/data/


# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: outputs # ${hydra:runtime.output_dir}

data_dir: data/
# path to working directory
# work_dir: ${hydra:runtime.cwd}

mano_dir: "assets/mano/"

object_mesh_dir: "data/HOT3D-CLIP/object_models_eval/"